name: Laravel Pint
on:
  - pull_request
  - push
jobs:
  pint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Fetch main branch
        run: git fetch origin main

      - name: Show diff with main
        run: git diff --name-only --diff-filter=AM origin/main...HEAD

      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@2.5
        with:
          verboseMode: true
          onlyDiff: "main"

      - uses: stefanzweifel/git-auto-commit-action@v6
        commit_message: "style: pint fixes"
