name: Laravel Pint
on:
  - pull_request
  - push
jobs:
  pint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@2.5
        with:
          verboseMode: true

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "style: pint fixes"
